---
- name: Installing Nginx
  hosts: web
  gather_facts: no
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
                 name: nginx
                 state: present
                 use_backend: auto

    - name: Enable and start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

